version: '1.0'

services: 
    web:
      build: .
      depends_on:
        - database
      ports: 
        - "5000:5000"

    database:
      image: postgres
      restart: always
      ports: 
        - "5432:5432"
      environment: 
        - "POSTGRES_USER=postgres"
        - "POSTGRES_PASSWORD=secret"
      volumes: 
        - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        - ./pgdata:/var/lib/postgresql/data

